#! /usr/bin/env bash
#############################
#
#  Author: Abbas Abdulmalik
#  Created: March 18, 2016
#  Revised: August 7, 2017[by Frank Smith]
#  Original Filename: apm [renamed fpm]
#  Purpose: download JS modules from my Github modules repo
#  Notes: Sudo command MUST be recognized by linux environment.
#
#############################
BASE="https://franksmith22.github.io/modules/"
if [ "$1" = "" ];
 then
  clear
  echo
  echo You must provide the name of the remote JS module.
  echo Example: $(basename $0) mymodule
  echo "(this gets the remote file mymodule.js)"
  echo
  exit 1
fi
  echo 
  echo "Base path is ${BASE}" 
if [[ ! -d "modules" && ! -f "modules"  ]];
 then
  echo "making modules directory"
  sudo mkdir modules
  sudo chown $(whoami) modules
  sudo chgrp $(whoami) modules
  echo
fi
if [ -f "modules" ];
 then
  echo
  echo "You have a 'modules' file, so can't make modules directory."
  echo
  exit 1
fi
###################################| Add filename extensions for js files |#####################################
rm temp 2>/dev/null
for ARG in $@;
  do 
    echo ${ARG} | egrep -v "\..{1,}$" >> temp   
  done


rm finalnames 2>/dev/null
for NAME in $(cat temp);
  do
    echo ${NAME}.js >> finalnames
  done


for ARG in $@;
  do 
    echo ${ARG} | egrep "\..{1,}$" >> finalnames
  done
cat finalnames

###################################|   Done adding filename extensions    |#####################################
for MODULE in $(cat finalnames);
 do
  sudo wget -O modules/${MODULE} "${BASE}${MODULE}"
  if [ $? -ne 0 ];
   then sudo rm modules/${MODULE}
  fi
  sudo chown $(whoami) modules/${MODULE} 2>/dev/null
  sudo chgrp $(whoami) modules/${MODULE} 2>/dev/null
 done
rm finalnames 2>/dev/null
rm temp 2>/dev/null 
